### ISSUE TITLE
Promises?

### ISSUE THREAD

**Issue by Bob-Thomas** [NightfallAlicorn/urban-dictionary#1]
Wouldn't it be nice to have the requests return a promise object with that get rejected and resolved based on  the result

**Comment by NightfallAlicorn** [comment]
I've had people mention the promise object. However, I'm still learning how they work at the moment. I'm aware they are becoming a future method for handling callbacks. I would have to plan either to update the current repository with promise or make a separate repository for it.

**Comment by NightfallAlicorn** [comment]
I've split the repository and published a promise object, ES6 version, of this module here: https://github.com/NightfallAlicorn/urban-dictionary-es6

**Comment by haykam821** [comment]
It seems that promises have been added as of 5094e9dfc805210b2c4bc4fa4868ebe872728931.
