### ISSUE TITLE
Failed to parse retrieved Urban Dictionary JSON.

### ISSUE THREAD

**Issue by VikkiVuk** [NightfallAlicorn/urban-dictionary#10]
Um so im trying to implement this into my bot and i used the code that was specified on the npm page but it gives me this error `Failed to parse retrieved Urban Dictionary JSON.` Help?

**Comment by NightfallAlicorn** [comment]
> Um so im trying to implement this into my bot and i used the code that was specified on the npm page but it gives me this error `Failed to parse retrieved Urban Dictionary JSON.` Help?

It seems api.urbandictionary.com have stopped supporting http protocol. I've released a fix that now uses https.

Try downloading the updated version.

**Comment by NightfallAlicorn** [comment]
It's been over a week and I've heard no further reports of the issue. I presume the fix has worked.

Closing issue.
