### ISSUE TITLE
Defid works again

### ISSUE THREAD

**Issue by eaaliprantis** [NightfallAlicorn/urban-dictionary#3]
Good Afternoon,

I queried a word against the API (http://api.urbandictionary.com/v0/define?defid=332927 ) and it returns a response.  Is there any way we could add it back in?

Thank you.

Best Regards,

Manny

**Comment by NightfallAlicorn** [comment]
Thank you for informing me. I've re-added the method to the module along with the update promise object and JSDoc additions.

I apologise for the inconvenience this may had caused.

Nova
