### ISSUE TITLE
Unable to send request for definitions. Status code: '500'

### ISSUE THREAD

**Issue by gco360** [NightfallAlicorn/urban-dictionary#7]
well i get this 
**`Unable to send request for definitions. Status code: '500'`** 
, i hope if you can fix it

**Comment by NightfallAlicorn** [comment]
I've tested my examples under the README.md file and they seem fine. Their site must had temporary gone down. It ends to happen once a while. If the issue still occurs try using one of my examples on its own. Although code 500 error should be on the server side from what I've read.

**Comment by NightfallAlicorn** [comment]
There hasn't been any new replies for a couple of months. I may add a error catch message that the server may be down in the near future since this does pop up once a while. Closing issue.
