### ISSUE TITLE
New endpoint

### ISSUE THREAD

**Issue by theabbie** [NightfallAlicorn/urban-dictionary#8]
`https://api.urbandictionary.com/v0/words_of_the_day`

**Comment by theabbie** [comment]
Autocomplete Endpoint

`https://api.urbandictionary.com/v0/autocomplete-extra?term={term}`

**Comment by NightfallAlicorn** [comment]
> Autocomplete Endpoint
> 
> `https://api.urbandictionary.com/v0/autocomplete-extra?term={term}`

Based from your quoted method. I've found that this also works:

`http://api.urbandictionary.com/v0/autocomplete?term={term}`

It looks like Urban have updated the json data. So some things may not work correctly at the moment.

Also I need to update the code with the new styles from StandardJS.

**Comment by theabbie** [comment]
@NightfallAlicorn Urban dictionary has a mobile app, I tried decompiling it to find more endpoints,

I have found this extremely large JS file which contains all endpoints but is highly obfuscated,

![https://d1wp6m56sqw74a.cloudfront.net/@urbandictionary/urbandictionary-app/3.5.1/e8b10f071d288b8d3056e85b5ce6bbb0-35.0.0-android.js](https://d1wp6m56sqw74a.cloudfront.net/@urbandictionary/urbandictionary-app/3.5.1/e8b10f071d288b8d3056e85b5ce6bbb0-35.0.0-android.js)

It had only 6 endpoints, `random`, `define`, `words_of_the_day`, `vote`, `autocomplete-extra`, `push_token`

So, I guess, these are all, If there are authenticated endpoints, that would be great, but the mobile app doesn't allow logging in.

**Comment by NightfallAlicorn** [comment]
Method additions and fixes are nearly ready for release. Closing issue.
